name: ci-spring-workflow
on: push
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - run: mvn clean install
      - run: java -jar ./target/example-spring.jar